config/routes.rb
Rails.application.routes.draw do
  resources :tokens
  resources :treasures

  post 'treasure_hunt' => 'api#check_coordinates', format: :json
  root 'treasures#index'

end

app/models/concerns/numeric_helper.rb
module NumericHelper
  extend ActiveSupport::Concern

  def convert_coordinates(coord)
    if coord.to_s =~ /^[-+]?\d*\.?\d*?$/
      coord
    else
      coord     = coord.to_s
      direction = coord[-1, 1].downcase
      coord     = coord.chop.gsub(' ', '').to_f

      if ['w', 's'].include?(direction)
        coord = coord * -1
      end

      coord
    end
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/treasure.rb
class Treasure < ActiveRecord::Base
  include NumericHelper

  reverse_geocoded_by :latitude, :longtitude
  validates :longtitude, presence: true, if: :longtitude
  validates :latitude, presence: true, if: :latitude

  before_save :convert_compass_coordinates

  attr_accessor :long, :lat

  def convert_compass_coordinates

    self.latitude   = convert_coordinates(self.lat)
    self.longtitude = convert_coordinates(self.long)
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  include NumericHelper

  before_filter :check_auth

  def check_coordinates
    latitude   = convert_coordinates(params[:latitude])
    longtitude = convert_coordinates(params[:longtitude])
    email      = params[:email]

    if latitude.present? and longtitude.present? and email.present?
      @treasure = Treasure.near([latitude.to_f, longtitude.to_f], 1000000, :order => "distance", :units => :km).first
      distance  = @treasure.distance_from([latitude.to_f, longtitude.to_f], :km) * 1000 #value in km
      distance  = distance.round

      if distance <= 5
        @treasure.founded += 1
        @treasure.save
        TreasureMailer.inform_user(email, @treasure.founded).deliver_later
      end

      render json: {
             status:   'ok',
             distance: distance
             }
    else
      render json: {status: 'error', distance: -1, error: 'error description'}
    end
  end

  def check_auth
    unless params[:token].present? and Token.find_by_token(params[:token]).present?
      render json: {status: 'authentication failed'}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/numeric_helper.rb
module NumericHelper
  extend ActiveSupport::Concern

  def convert_coordinates(coord)
    if coord.to_s =~ /^[-+]?\d*\.?\d*?$/
      coord
    elsif coord.to_s =~ /^(-?\d{1,2}\.\d).*[a-zA-Z]$/
      coord     = coord.to_s
      direction = coord[-1, 1].downcase
      coord     = coord.chop.gsub(' ', '').to_f

      if ['w', 's'].include?(direction)
        coord = coord * -1
      end

      coord
    else
      nil
    end
  end

end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url, notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      params.require(:token).permit(:token)
    end
end

app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController
  before_action :set_treasure, only: [:show, :edit, :update, :destroy]

  # GET /treasures
  # GET /treasures.json
  def index
    @treasures = Treasure.all
  end

  # GET /treasures/1
  # GET /treasures/1.json
  def show
  end

  # GET /treasures/new
  def new
    @treasure = Treasure.new
  end

  # GET /treasures/1/edit
  def edit
  end

  # POST /treasures
  # POST /treasures.json
  def create
    @treasure = Treasure.new(treasure_params)

    respond_to do |format|
      if @treasure.save
        format.html { redirect_to @treasure, notice: 'Treasure was successfully created.' }
        format.json { render :show, status: :created, location: @treasure }
      else
        format.html { render :new }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treasures/1
  # PATCH/PUT /treasures/1.json
  def update
    respond_to do |format|
      if @treasure.update(treasure_params)
        format.html { redirect_to @treasure, notice: 'Treasure was successfully updated.' }
        format.json { render :show, status: :ok, location: @treasure }
      else
        format.html { render :edit }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treasures/1
  # DELETE /treasures/1.json
  def destroy
    @treasure.destroy
    respond_to do |format|
      format.html { redirect_to treasures_url, notice: 'Treasure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treasure
      @treasure = Treasure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treasure_params
      params.require(:treasure).permit(:long, :lat)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/treasures_helper.rb
module TreasuresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreasureHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tokens/_form.html.erb
<%= form_for(@token) do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.token %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>
<%= link_to 'Manage treasures', treasures_path %>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @token.token %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>

app/views/treasures/_form.html.erb
<%= form_for(@treasure) do |f| %>
  <% if @treasure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treasure.errors.count, "error") %> prohibited this treasure from being saved:</h2>

      <ul>
      <% @treasure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :longtitude %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treasures/edit.html.erb
<h1>Editing Treasure</h1>

<%= render 'form' %>

<%= link_to 'Show', @treasure %> |
<%= link_to 'Back', treasures_path %>

app/views/treasures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Treasures</h1>

<table>
  <thead>
    <tr>
      <th>Longtitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treasures.each do |treasure| %>
      <tr>
        <td><%= treasure.longtitude %></td>
        <td><%= treasure.latitude %></td>
        <td><%= link_to 'Show', treasure %></td>
        <td><%= link_to 'Edit', edit_treasure_path(treasure) %></td>
        <td><%= link_to 'Destroy', treasure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treasure', new_treasure_path %>
<%= link_to 'Manage tokens', tokens_path %>

app/views/treasures/new.html.erb
<h1>New Treasure</h1>

<%= render 'form' %>

<%= link_to 'Back', treasures_path %>

app/views/treasures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Longtitude:</strong>
  <%= @treasure.longtitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @treasure.latitude %>
</p>

<%= link_to 'Edit', edit_treasure_path(@treasure) %> |
<%= link_to 'Back', treasures_path %>